# Dockerfile.gui
FROM python:3.10-slim
WORKDIR /app

# Installer les dépendances GUI
COPY requirements.txt .
RUN pip install --no-cache-dir streamlit plotly pandas requests

# Copier le code GUI
COPY src/gui.py ./src/gui.py

EXPOSE 8501
CMD ["streamlit", "run", "src/gui.py", "--server.port=8501", "--server.address=0.0.0.0"]
