name: Build & Push Docker

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # # 1) Installer DVC
      # - name: Install DVC
      #   run: pip install dvc

      # # 2) Récupérer les modèles
      # - name: DVC pull models
      #   run: dvc pull model/production_model.h5 model/production_model.tflite

      # 3) Build & push Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/bitcoin-pi-inference:latest
